# Generated by Django 4.1.7 on 2023-03-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="idade",
            new_name="idade_usuario",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="nome",
            new_name="nome_usuario",
        ),
    ]
